@host = http://localhost:8000/api/v1/user
@hostcompany = http://localhost:8000/api/v1/company
@hostjob = http://localhost:8000/api/v1/job
@hostapplication = http://localhost:8000/api/v1/application

POST {{host}}/register
Content-Type: application/json

{
    "fullname":"vijay",
    "email":"vijayji@gmail.com",
    "phoneNumber":"1234567890",
    "password":"vijay123",
    "role":"recruiter"
}

###

POST {{host}}/register
Content-Type: application/json

{
    "fullname":"Vijay",
    "email":"vijay@gmail.com",
    "phoneNumber":"1234567890",
    "password":"vijay123",
    "role":"student"
}

###
POST {{host}}/login
Content-Type: application/json

{
    "email":"vijayji@gmail.com",
    "password":"vijay123",
    "role":"recruiter"
}
###
POST {{host}}/login
Content-Type: application/json

{
    "email":"vijay@gmail.com",
    "password":"vijay123",
    "role":"student"
}


###

POST {{host}}/profile/update
Content-Type: application/json

{
    "fullname":"vijay ji"
 
}



###
GET {{host}}/logout

###

POST {{hostcompany}}/registerCompany
Content-Type: application/json

# {
#     "companyName":"vijay di Company"
# }
{
    "companyName":"Intel"
}


###

GET {{hostcompany}}/get

###

GET {{hostcompany}}/get/6782b20d034b8c02155cd965
###

PUT {{hostcompany}}/update/6782a5366cba035cb54bbd30
Content-Type: application/json

{
    "name":"micromax"
}

###
POST {{hostjob}}/post
Content-Type: application/json

{
    "title":"Backend Developer",
    "description":"I want Backend developer for my company",
    "requirements":"Reactjs, Shadcnui, Api Testing",
    "salary":"12",
    "location":"agra",
    "jobType":"Full Time",
    "experience":1,
    "position":12,
    "companyId":"6782b3503a2c0842b6d56f73"
}

###

GET {{hostjob}}/get
###

GET {{hostjob}}/getadminjob

###

GET {{hostjob}}/get/6786683884cc609d0ecd07b5

###
GET {{hostapplication}}/apply/67865e6f90c0469b8e960013

###
GET {{hostapplication}}/get

###
GET {{hostapplication}}/67ec36a734a9f7bc59d57a52/applicants

###
POST {{hostapplication}}/status/67868f46172bff46d27d7688/update
Content-Type: application/json

{
    "status":"Accepted"
}


